Remove a invalid parameter setting in test code
The regression test said the following ERROR from v15 beta1.

 ERROR:  invalid configuration parameter name "pg_hint_plan.debug_level"
 DETAIL:  "pg_hint_plan" is a reserved prefix.